### ISSUE TITLE
Modules aren't following hashicorp best practice

### ISSUE THREAD

**Issue by crawfs** [kuhlman-labs/terraform-azurerm-landing-zone#24]
Hey mate, thought I'd just give you a heads up about the module use in this repo, according to the terraform documentation they advise to avoid using modules that are just the name of the resources https://www.terraform.io/docs/modules/index.html#when-to-write-a-module 

> If you have trouble finding a name for your module that isn't the same as the main resource type inside it, that may be a sign that your module is not creating any new abstraction and so the module is adding unnecessary complexity. Just use the resource type directly in the calling module instead.

Which is what's going on here: https://github.com/kuhlman-labs/terraform-azurerm-landing-zone/blob/master/modules/network_spoke/main.tf each of those module resources for virtual network, resource group, vnet peering etc should realistically be resource blocks instead.

To speak from personal experience I've recently been working on getting terraform adopted in our workplace and I've found that gratuitous use of modules in this manner tends to confuse people more often than not, having a module for a network spoke makes sense, but the resources defined in that module shouldn't also be modules.

**Comment by kuhlman-labs** [comment]
Hey @crawfs thank you for the feedback! 

I chose to create single resource modules for a few reasons.

- I wanted to treat each resource as a function that I could call with a few parameters for what the module required. To do this I had to create each resource module to be as flexible as possible in its configuration, earlier versions of Terraform made this next to impossible but with the inclusion of things like `dynamic blocks` and `null `values I've had much more success.

- Defining the naming conventions in the resource modules makes it so that naming conventions are consistent no matter what module is calling it. I've seen some approaches where a naming module is created to handle this and I'm not opposed to this idea but so far I've been happy with this approach.

- By reducing the lines of code in the module compositions my hope is that it makes it easier to read and understand the resources being used.

I am not married to this approach by any means but in my experience so far I've found it easier to pull together modules using this method, but time will tell :)

Thanks again for the feedback, always appreciate another viewpoint.

**Comment by crawfs** [comment]
No worries, always happy to give constructive feedback. I've particularly been avoiding this method recently because when they update the azurerm provider they often introduce breaking changes for new features, which can result in a large number of deployments being broken by trying to add a feature to a single module in this repository.
